### ISSUE TITLE
Better detection of started/stopped services

### ISSUE THREAD

**Issue by NanoSector** [Yoshi2889/Brewed#1]
Brewed tries to detect stopped services by watching for file deletion events on the plist file specified by Homebrew:
https://github.com/Yoshi2889/Brewed/blob/e0f244be15d33be41f7e49431bdc3afe3b6a5908/Brewed/Model/ManagedServices.swift#L39-L42

While this works in many cases, it only works for stopped services. Right now services which get started after Brewed won't get detected.

This may be solvable by letting Brewed guess plist locations; these seem to be set in the format `homebrew.mxcl.{formula}`.

**Tasks**:
- [ ] Make brewed detect services stopped via `brew services stop`, when started through either run or start
- [x] Make Brewed detect services started via `brew services start`
- [ ] Make Brewed detect services started via `brew services run`
- [ ] Do not pointlessly watch plist files in `/usr/local/opt`

**Comment by NanoSector** [comment]
We cannot monitor for creation of files by creating a file monitor at the expected locations since code in FileMonitor expects the files to actually exist. An alternative approach would be to somehow monitor the agent/daemon directories for file creation events and filter based on the expected name.

**Comment by NanoSector** [comment]
#4 fixed part of this, however there still remains an issue when a service is just 'run' and not actually started. Homebrew then points to the /usr/local/opt/ directory and these files will always exist. Brewed watches these, but pointlessly.
