### ISSUE TITLE
Log viewer

### ISSUE THREAD

**Issue by NanoSector** [Yoshi2889/Brewed#11]
Allow log files to be read in the app.

I'm not sure if log file paths follow a standard pattern; if so, use that, otherwise include a list of possible log file locations per formula in the app. Preferably in a Plist file included with the app.

**Tasks**

- [ ] Detect log files
- [ ] Show list of log files to the user
- [ ] Include last modified date in this interface
- [ ] Show log file
- [ ] Watch log file (and make sure the text view doesn't completely reset)
- [ ] Delete log files? (Might be way outside the scope of this app)
